# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM golang:1.23 AS builder
WORKDIR /src/order
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -gcflags=all="-N -l" -o /order

FROM alpine:latest
COPY --from=builder /order /order
CMD ["/order"]


# docker buildx build --platform linux/amd64 \
#-t <LOCATION>-docker.pkg.dev/<PROJECT-ID>/<REPO-NAME>/<IMAGE> .
