// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: couponservice.proto

package genproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponTypes int32

const (
	CouponTypes_COUPON_TYPE_UNSPECIFICED CouponTypes = 0
	// Discount is a fixed amount, not a percentage.
	CouponTypes_COUPON_TYPE_DISCOUNT      CouponTypes = 1
	CouponTypes_COUPON_TYPE_FREE_DELIVERY CouponTypes = 2
)

// Enum value maps for CouponTypes.
var (
	CouponTypes_name = map[int32]string{
		0: "COUPON_TYPE_UNSPECIFICED",
		1: "COUPON_TYPE_DISCOUNT",
		2: "COUPON_TYPE_FREE_DELIVERY",
	}
	CouponTypes_value = map[string]int32{
		"COUPON_TYPE_UNSPECIFICED":  0,
		"COUPON_TYPE_DISCOUNT":      1,
		"COUPON_TYPE_FREE_DELIVERY": 2,
	}
)

func (x CouponTypes) Enum() *CouponTypes {
	p := new(CouponTypes)
	*p = x
	return p
}

func (x CouponTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_couponservice_proto_enumTypes[0].Descriptor()
}

func (CouponTypes) Type() protoreflect.EnumType {
	return &file_couponservice_proto_enumTypes[0]
}

func (x CouponTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponTypes.Descriptor instead.
func (CouponTypes) EnumDescriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{0}
}

type Coupon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Types CouponTypes            `protobuf:"varint,1,opt,name=types,proto3,enum=ihavefood.CouponTypes" json:"types,omitempty"`
	Code  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// The discount amount, required if coupon_type is COUPON_TYPE_DISCOUNT.
	// The server will ignore this field if coupon_type is COUPON_TYPE_FREE_DELIVERY.
	Discount int32 `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	// Number of seconds until the coupon expires.
	ExpiresIn     int64 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	QuantityCount int32 `protobuf:"varint,5,opt,name=quantity_count,json=quantityCount,proto3" json:"quantity_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_couponservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{0}
}

func (x *Coupon) GetTypes() CouponTypes {
	if x != nil {
		return x.Types
	}
	return CouponTypes_COUPON_TYPE_UNSPECIFICED
}

func (x *Coupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Coupon) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Coupon) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *Coupon) GetQuantityCount() int32 {
	if x != nil {
		return x.QuantityCount
	}
	return 0
}

type AddCouponRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CouponTypes CouponTypes            `protobuf:"varint,1,opt,name=coupon_types,json=couponTypes,proto3,enum=ihavefood.CouponTypes" json:"coupon_types,omitempty"`
	Discount    int32                  `protobuf:"varint,2,opt,name=discount,proto3" json:"discount,omitempty"`
	// The coupon expiration time in hours from now.
	// For example expire_in_hour is 72 means the coupon will be expired
	// in 3 days (72 hours) from now.
	ExpireInHour  int32 `protobuf:"varint,3,opt,name=expire_in_hour,json=expireInHour,proto3" json:"expire_in_hour,omitempty"`
	Quantity      int32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCouponRequest) Reset() {
	*x = AddCouponRequest{}
	mi := &file_couponservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCouponRequest) ProtoMessage() {}

func (x *AddCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCouponRequest.ProtoReflect.Descriptor instead.
func (*AddCouponRequest) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{1}
}

func (x *AddCouponRequest) GetCouponTypes() CouponTypes {
	if x != nil {
		return x.CouponTypes
	}
	return CouponTypes_COUPON_TYPE_UNSPECIFICED
}

func (x *AddCouponRequest) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *AddCouponRequest) GetExpireInHour() int32 {
	if x != nil {
		return x.ExpireInHour
	}
	return 0
}

func (x *AddCouponRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponRequest) Reset() {
	*x = GetCouponRequest{}
	mi := &file_couponservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponRequest) ProtoMessage() {}

func (x *GetCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponRequest.ProtoReflect.Descriptor instead.
func (*GetCouponRequest) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetCouponRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*Coupon              `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsResponse) Reset() {
	*x = ListCouponsResponse{}
	mi := &file_couponservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsResponse) ProtoMessage() {}

func (x *ListCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsResponse.ProtoReflect.Descriptor instead.
func (*ListCouponsResponse) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{3}
}

func (x *ListCouponsResponse) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type RedeemCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCouponRequest) Reset() {
	*x = RedeemCouponRequest{}
	mi := &file_couponservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCouponRequest) ProtoMessage() {}

func (x *RedeemCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCouponRequest.ProtoReflect.Descriptor instead.
func (*RedeemCouponRequest) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{4}
}

func (x *RedeemCouponRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RedeemCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCouponResponse) Reset() {
	*x = RedeemCouponResponse{}
	mi := &file_couponservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCouponResponse) ProtoMessage() {}

func (x *RedeemCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couponservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCouponResponse.ProtoReflect.Descriptor instead.
func (*RedeemCouponResponse) Descriptor() ([]byte, []int) {
	return file_couponservice_proto_rawDescGZIP(), []int{5}
}

func (x *RedeemCouponResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_couponservice_proto protoreflect.FileDescriptor

const file_couponservice_proto_rawDesc = "" +
	"\n" +
	"\x13couponservice.proto\x12\tihavefood\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x01\n" +
	"\x06Coupon\x12,\n" +
	"\x05types\x18\x01 \x01(\x0e2\x16.ihavefood.CouponTypesR\x05types\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\x05R\bdiscount\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12%\n" +
	"\x0equantity_count\x18\x05 \x01(\x05R\rquantityCount\"\xab\x01\n" +
	"\x10AddCouponRequest\x129\n" +
	"\fcoupon_types\x18\x01 \x01(\x0e2\x16.ihavefood.CouponTypesR\vcouponTypes\x12\x1a\n" +
	"\bdiscount\x18\x02 \x01(\x05R\bdiscount\x12$\n" +
	"\x0eexpire_in_hour\x18\x03 \x01(\x05R\fexpireInHour\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"&\n" +
	"\x10GetCouponRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"B\n" +
	"\x13ListCouponsResponse\x12+\n" +
	"\acoupons\x18\x01 \x03(\v2\x11.ihavefood.CouponR\acoupons\")\n" +
	"\x13RedeemCouponRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"0\n" +
	"\x14RedeemCouponResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*d\n" +
	"\vCouponTypes\x12\x1c\n" +
	"\x18COUPON_TYPE_UNSPECIFICED\x10\x00\x12\x18\n" +
	"\x14COUPON_TYPE_DISCOUNT\x10\x01\x12\x1d\n" +
	"\x19COUPON_TYPE_FREE_DELIVERY\x10\x022\xef\x02\n" +
	"\rCouponService\x12[\n" +
	"\vListCoupons\x12\x16.google.protobuf.Empty\x1a\x1e.ihavefood.ListCouponsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/coupons\x12X\n" +
	"\tGetCoupon\x12\x1b.ihavefood.GetCouponRequest\x1a\x11.ihavefood.Coupon\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/coupons/{code}\x12T\n" +
	"\tAddCoupon\x12\x1b.ihavefood.AddCouponRequest\x1a\x11.ihavefood.Coupon\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/coupons\x12Q\n" +
	"\fRedeemCoupon\x12\x1e.ihavefood.RedeemCouponRequest\x1a\x1f.ihavefood.RedeemCouponResponse\"\x00B\vZ\t/genprotob\x06proto3"

var (
	file_couponservice_proto_rawDescOnce sync.Once
	file_couponservice_proto_rawDescData []byte
)

func file_couponservice_proto_rawDescGZIP() []byte {
	file_couponservice_proto_rawDescOnce.Do(func() {
		file_couponservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couponservice_proto_rawDesc), len(file_couponservice_proto_rawDesc)))
	})
	return file_couponservice_proto_rawDescData
}

var file_couponservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_couponservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_couponservice_proto_goTypes = []any{
	(CouponTypes)(0),             // 0: ihavefood.CouponTypes
	(*Coupon)(nil),               // 1: ihavefood.Coupon
	(*AddCouponRequest)(nil),     // 2: ihavefood.AddCouponRequest
	(*GetCouponRequest)(nil),     // 3: ihavefood.GetCouponRequest
	(*ListCouponsResponse)(nil),  // 4: ihavefood.ListCouponsResponse
	(*RedeemCouponRequest)(nil),  // 5: ihavefood.RedeemCouponRequest
	(*RedeemCouponResponse)(nil), // 6: ihavefood.RedeemCouponResponse
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_couponservice_proto_depIdxs = []int32{
	0, // 0: ihavefood.Coupon.types:type_name -> ihavefood.CouponTypes
	0, // 1: ihavefood.AddCouponRequest.coupon_types:type_name -> ihavefood.CouponTypes
	1, // 2: ihavefood.ListCouponsResponse.coupons:type_name -> ihavefood.Coupon
	7, // 3: ihavefood.CouponService.ListCoupons:input_type -> google.protobuf.Empty
	3, // 4: ihavefood.CouponService.GetCoupon:input_type -> ihavefood.GetCouponRequest
	2, // 5: ihavefood.CouponService.AddCoupon:input_type -> ihavefood.AddCouponRequest
	5, // 6: ihavefood.CouponService.RedeemCoupon:input_type -> ihavefood.RedeemCouponRequest
	4, // 7: ihavefood.CouponService.ListCoupons:output_type -> ihavefood.ListCouponsResponse
	1, // 8: ihavefood.CouponService.GetCoupon:output_type -> ihavefood.Coupon
	1, // 9: ihavefood.CouponService.AddCoupon:output_type -> ihavefood.Coupon
	6, // 10: ihavefood.CouponService.RedeemCoupon:output_type -> ihavefood.RedeemCouponResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_couponservice_proto_init() }
func file_couponservice_proto_init() {
	if File_couponservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couponservice_proto_rawDesc), len(file_couponservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couponservice_proto_goTypes,
		DependencyIndexes: file_couponservice_proto_depIdxs,
		EnumInfos:         file_couponservice_proto_enumTypes,
		MessageInfos:      file_couponservice_proto_msgTypes,
	}.Build()
	File_couponservice_proto = out.File
	file_couponservice_proto_goTypes = nil
	file_couponservice_proto_depIdxs = nil
}
