// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: orderservice.proto

package genproto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethods int32

const (
	PaymentMethods_PAYMENT_METHOD_UNSPECIFIED PaymentMethods = 0
	PaymentMethods_PAYMENT_METHOD_CASH        PaymentMethods = 1
	PaymentMethods_PAYMENT_METHOD_CREDIT_CARD PaymentMethods = 2
	PaymentMethods_PAYMENT_METHOD_PROMPT_PAY  PaymentMethods = 3
)

// Enum value maps for PaymentMethods.
var (
	PaymentMethods_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CASH",
		2: "PAYMENT_METHOD_CREDIT_CARD",
		3: "PAYMENT_METHOD_PROMPT_PAY",
	}
	PaymentMethods_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CASH":        1,
		"PAYMENT_METHOD_CREDIT_CARD": 2,
		"PAYMENT_METHOD_PROMPT_PAY":  3,
	}
)

func (x PaymentMethods) Enum() *PaymentMethods {
	p := new(PaymentMethods)
	*p = x
	return p
}

func (x PaymentMethods) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethods) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_proto_enumTypes[0].Descriptor()
}

func (PaymentMethods) Type() protoreflect.EnumType {
	return &file_orderservice_proto_enumTypes[0]
}

func (x PaymentMethods) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethods.Descriptor instead.
func (PaymentMethods) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_UNPAID PaymentStatus = 0
	PaymentStatus_PAID   PaymentStatus = 1
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "UNPAID",
		1: "PAID",
	}
	PaymentStatus_value = map[string]int32{
		"UNPAID": 0,
		"PAID":   1,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_orderservice_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_PENDING         OrderStatus = 0
	OrderStatus_PREPARING_ORDER OrderStatus = 1
	OrderStatus_FINDING_RIDER   OrderStatus = 2
	OrderStatus_WAIT_FOR_PICKUP OrderStatus = 3
	OrderStatus_ONGOING         OrderStatus = 4
	OrderStatus_DELIVERED       OrderStatus = 5
	OrderStatus_CANCELLED       OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PREPARING_ORDER",
		2: "FINDING_RIDER",
		3: "WAIT_FOR_PICKUP",
		4: "ONGOING",
		5: "DELIVERED",
		6: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":         0,
		"PREPARING_ORDER": 1,
		"FINDING_RIDER":   2,
		"WAIT_FOR_PICKUP": 3,
		"ONGOING":         4,
		"DELIVERED":       5,
		"CANCELLED":       6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orderservice_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{2}
}

type PlaceOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id for idempotency.
	RequestId       string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrderId         string           `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId      string           `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantId      string           `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Items           []*OrderItem     `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	CouponCode      string           `protobuf:"bytes,6,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	CouponDiscount  int32            `protobuf:"varint,7,opt,name=coupon_discount,json=couponDiscount,proto3" json:"coupon_discount,omitempty"`
	DeliveryFee     int32            `protobuf:"varint,8,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	Total           int32            `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	CustomerAddress *Address         `protobuf:"bytes,10,opt,name=customer_address,json=customerAddress,proto3" json:"customer_address,omitempty"`
	MerchantAddress *Address         `protobuf:"bytes,11,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	CustomerContact *ContactInfo     `protobuf:"bytes,12,opt,name=customer_contact,json=customerContact,proto3" json:"customer_contact,omitempty"`
	PaymentMethods  PaymentMethods   `protobuf:"varint,13,opt,name=payment_methods,json=paymentMethods,proto3,enum=ihavefood.PaymentMethods" json:"payment_methods,omitempty"`
	PaymentStatus   PaymentStatus    `protobuf:"varint,14,opt,name=payment_status,json=paymentStatus,proto3,enum=ihavefood.PaymentStatus" json:"payment_status,omitempty"`
	OrderStatus     OrderStatus      `protobuf:"varint,15,opt,name=order_status,json=orderStatus,proto3,enum=ihavefood.OrderStatus" json:"order_status,omitempty"`
	OrderTimestamps *OrderTimestamps `protobuf:"bytes,16,opt,name=order_timestamps,json=orderTimestamps,proto3" json:"order_timestamps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaceOrder) Reset() {
	*x = PlaceOrder{}
	mi := &file_orderservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrder) ProtoMessage() {}

func (x *PlaceOrder) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrder.ProtoReflect.Descriptor instead.
func (*PlaceOrder) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrder) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrder) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PlaceOrder) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *PlaceOrder) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlaceOrder) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *PlaceOrder) GetCouponDiscount() int32 {
	if x != nil {
		return x.CouponDiscount
	}
	return 0
}

func (x *PlaceOrder) GetDeliveryFee() int32 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *PlaceOrder) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PlaceOrder) GetCustomerAddress() *Address {
	if x != nil {
		return x.CustomerAddress
	}
	return nil
}

func (x *PlaceOrder) GetMerchantAddress() *Address {
	if x != nil {
		return x.MerchantAddress
	}
	return nil
}

func (x *PlaceOrder) GetCustomerContact() *ContactInfo {
	if x != nil {
		return x.CustomerContact
	}
	return nil
}

func (x *PlaceOrder) GetPaymentMethods() PaymentMethods {
	if x != nil {
		return x.PaymentMethods
	}
	return PaymentMethods_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PlaceOrder) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_UNPAID
}

func (x *PlaceOrder) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_PENDING
}

func (x *PlaceOrder) GetOrderTimestamps() *OrderTimestamps {
	if x != nil {
		return x.OrderTimestamps
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orderservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_orderservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrderTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CompleteTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTimestamps) Reset() {
	*x = OrderTimestamps{}
	mi := &file_orderservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTimestamps) ProtoMessage() {}

func (x *OrderTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTimestamps.ProtoReflect.Descriptor instead.
func (*OrderTimestamps) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{3}
}

func (x *OrderTimestamps) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *OrderTimestamps) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *OrderTimestamps) GetCompleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompleteTime
	}
	return nil
}

type ListOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderHistoryRequest) Reset() {
	*x = ListOrderHistoryRequest{}
	mi := &file_orderservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderHistoryRequest) ProtoMessage() {}

func (x *ListOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrderHistoryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type ListOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceOrders   []*PlaceOrder          `protobuf:"bytes,1,rep,name=place_orders,json=placeOrders,proto3" json:"place_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderHistoryResponse) Reset() {
	*x = ListOrderHistoryResponse{}
	mi := &file_orderservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderHistoryResponse) ProtoMessage() {}

func (x *ListOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderHistoryResponse) GetPlaceOrders() []*PlaceOrder {
	if x != nil {
		return x.PlaceOrders
	}
	return nil
}

type CreatePlaceOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	CouponCode      string                 `protobuf:"bytes,5,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	CustomerAddress *Address               `protobuf:"bytes,6,opt,name=customer_address,json=customerAddress,proto3" json:"customer_address,omitempty"`
	CustomerContact *ContactInfo           `protobuf:"bytes,7,opt,name=customer_contact,json=customerContact,proto3" json:"customer_contact,omitempty"`
	PaymentMethods  PaymentMethods         `protobuf:"varint,8,opt,name=payment_methods,json=paymentMethods,proto3,enum=ihavefood.PaymentMethods" json:"payment_methods,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePlaceOrderRequest) Reset() {
	*x = CreatePlaceOrderRequest{}
	mi := &file_orderservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceOrderRequest) ProtoMessage() {}

func (x *CreatePlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePlaceOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreatePlaceOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePlaceOrderRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePlaceOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePlaceOrderRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *CreatePlaceOrderRequest) GetCustomerAddress() *Address {
	if x != nil {
		return x.CustomerAddress
	}
	return nil
}

func (x *CreatePlaceOrderRequest) GetCustomerContact() *ContactInfo {
	if x != nil {
		return x.CustomerContact
	}
	return nil
}

func (x *CreatePlaceOrderRequest) GetPaymentMethods() PaymentMethods {
	if x != nil {
		return x.PaymentMethods
	}
	return PaymentMethods_PAYMENT_METHOD_UNSPECIFIED
}

var File_orderservice_proto protoreflect.FileDescriptor

const file_orderservice_proto_rawDesc = "" +
	"\n" +
	"\x12orderservice.proto\x12\tihavefood\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xff\x05\n" +
	"\n" +
	"PlaceOrder\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x05items\x18\x05 \x03(\v2\x14.ihavefood.OrderItemR\x05items\x12\x1f\n" +
	"\vcoupon_code\x18\x06 \x01(\tR\n" +
	"couponCode\x12'\n" +
	"\x0fcoupon_discount\x18\a \x01(\x05R\x0ecouponDiscount\x12!\n" +
	"\fdelivery_fee\x18\b \x01(\x05R\vdeliveryFee\x12\x14\n" +
	"\x05total\x18\t \x01(\x05R\x05total\x12=\n" +
	"\x10customer_address\x18\n" +
	" \x01(\v2\x12.ihavefood.AddressR\x0fcustomerAddress\x12=\n" +
	"\x10merchant_address\x18\v \x01(\v2\x12.ihavefood.AddressR\x0fmerchantAddress\x12A\n" +
	"\x10customer_contact\x18\f \x01(\v2\x16.ihavefood.ContactInfoR\x0fcustomerContact\x12B\n" +
	"\x0fpayment_methods\x18\r \x01(\x0e2\x19.ihavefood.PaymentMethodsR\x0epaymentMethods\x12?\n" +
	"\x0epayment_status\x18\x0e \x01(\x0e2\x18.ihavefood.PaymentStatusR\rpaymentStatus\x129\n" +
	"\forder_status\x18\x0f \x01(\x0e2\x16.ihavefood.OrderStatusR\vorderStatus\x12E\n" +
	"\x10order_timestamps\x18\x10 \x01(\v2\x1a.ihavefood.OrderTimestampsR\x0forderTimestamps\"T\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"F\n" +
	"\vContactInfo\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xcc\x01\n" +
	"\x0fOrderTimestamps\x12;\n" +
	"\vcreate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12?\n" +
	"\rcomplete_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcompleteTime\"w\n" +
	"\x17ListOrderHistoryRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId:;\x92A826{\"customer_id\":\"0cf361e1-4b44-483d-a159-54dabdf7e814\"}\"T\n" +
	"\x18ListOrderHistoryResponse\x128\n" +
	"\fplace_orders\x18\x01 \x03(\v2\x15.ihavefood.PlaceOrderR\vplaceOrders\"\x8d\x03\n" +
	"\x17CreatePlaceOrderRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x05items\x18\x04 \x03(\v2\x14.ihavefood.OrderItemR\x05items\x12\x1f\n" +
	"\vcoupon_code\x18\x05 \x01(\tR\n" +
	"couponCode\x12=\n" +
	"\x10customer_address\x18\x06 \x01(\v2\x12.ihavefood.AddressR\x0fcustomerAddress\x12A\n" +
	"\x10customer_contact\x18\a \x01(\v2\x16.ihavefood.ContactInfoR\x0fcustomerContact\x12B\n" +
	"\x0fpayment_methods\x18\b \x01(\x0e2\x19.ihavefood.PaymentMethodsR\x0epaymentMethods*\x88\x01\n" +
	"\x0ePaymentMethods\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CASH\x10\x01\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x02\x12\x1d\n" +
	"\x19PAYMENT_METHOD_PROMPT_PAY\x10\x03*%\n" +
	"\rPaymentStatus\x12\n" +
	"\n" +
	"\x06UNPAID\x10\x00\x12\b\n" +
	"\x04PAID\x10\x01*\x82\x01\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x13\n" +
	"\x0fPREPARING_ORDER\x10\x01\x12\x11\n" +
	"\rFINDING_RIDER\x10\x02\x12\x13\n" +
	"\x0fWAIT_FOR_PICKUP\x10\x03\x12\v\n" +
	"\aONGOING\x10\x04\x12\r\n" +
	"\tDELIVERED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x062\x81\x02\n" +
	"\fOrderService\x12~\n" +
	"\x10ListOrderHistory\x12\".ihavefood.ListOrderHistoryRequest\x1a#.ihavefood.ListOrderHistoryResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/orders/{customer_id}\x12q\n" +
	"\x10CreatePlaceOrder\x12\".ihavefood.CreatePlaceOrderRequest\x1a\x15.ihavefood.PlaceOrder\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/orders/place_orderB\vZ\t/genprotob\x06proto3"

var (
	file_orderservice_proto_rawDescOnce sync.Once
	file_orderservice_proto_rawDescData []byte
)

func file_orderservice_proto_rawDescGZIP() []byte {
	file_orderservice_proto_rawDescOnce.Do(func() {
		file_orderservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderservice_proto_rawDesc), len(file_orderservice_proto_rawDesc)))
	})
	return file_orderservice_proto_rawDescData
}

var file_orderservice_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orderservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orderservice_proto_goTypes = []any{
	(PaymentMethods)(0),              // 0: ihavefood.PaymentMethods
	(PaymentStatus)(0),               // 1: ihavefood.PaymentStatus
	(OrderStatus)(0),                 // 2: ihavefood.OrderStatus
	(*PlaceOrder)(nil),               // 3: ihavefood.PlaceOrder
	(*OrderItem)(nil),                // 4: ihavefood.OrderItem
	(*ContactInfo)(nil),              // 5: ihavefood.ContactInfo
	(*OrderTimestamps)(nil),          // 6: ihavefood.OrderTimestamps
	(*ListOrderHistoryRequest)(nil),  // 7: ihavefood.ListOrderHistoryRequest
	(*ListOrderHistoryResponse)(nil), // 8: ihavefood.ListOrderHistoryResponse
	(*CreatePlaceOrderRequest)(nil),  // 9: ihavefood.CreatePlaceOrderRequest
	(*Address)(nil),                  // 10: ihavefood.Address
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_orderservice_proto_depIdxs = []int32{
	4,  // 0: ihavefood.PlaceOrder.items:type_name -> ihavefood.OrderItem
	10, // 1: ihavefood.PlaceOrder.customer_address:type_name -> ihavefood.Address
	10, // 2: ihavefood.PlaceOrder.merchant_address:type_name -> ihavefood.Address
	5,  // 3: ihavefood.PlaceOrder.customer_contact:type_name -> ihavefood.ContactInfo
	0,  // 4: ihavefood.PlaceOrder.payment_methods:type_name -> ihavefood.PaymentMethods
	1,  // 5: ihavefood.PlaceOrder.payment_status:type_name -> ihavefood.PaymentStatus
	2,  // 6: ihavefood.PlaceOrder.order_status:type_name -> ihavefood.OrderStatus
	6,  // 7: ihavefood.PlaceOrder.order_timestamps:type_name -> ihavefood.OrderTimestamps
	11, // 8: ihavefood.OrderTimestamps.create_time:type_name -> google.protobuf.Timestamp
	11, // 9: ihavefood.OrderTimestamps.update_time:type_name -> google.protobuf.Timestamp
	11, // 10: ihavefood.OrderTimestamps.complete_time:type_name -> google.protobuf.Timestamp
	3,  // 11: ihavefood.ListOrderHistoryResponse.place_orders:type_name -> ihavefood.PlaceOrder
	4,  // 12: ihavefood.CreatePlaceOrderRequest.items:type_name -> ihavefood.OrderItem
	10, // 13: ihavefood.CreatePlaceOrderRequest.customer_address:type_name -> ihavefood.Address
	5,  // 14: ihavefood.CreatePlaceOrderRequest.customer_contact:type_name -> ihavefood.ContactInfo
	0,  // 15: ihavefood.CreatePlaceOrderRequest.payment_methods:type_name -> ihavefood.PaymentMethods
	7,  // 16: ihavefood.OrderService.ListOrderHistory:input_type -> ihavefood.ListOrderHistoryRequest
	9,  // 17: ihavefood.OrderService.CreatePlaceOrder:input_type -> ihavefood.CreatePlaceOrderRequest
	8,  // 18: ihavefood.OrderService.ListOrderHistory:output_type -> ihavefood.ListOrderHistoryResponse
	3,  // 19: ihavefood.OrderService.CreatePlaceOrder:output_type -> ihavefood.PlaceOrder
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_orderservice_proto_init() }
func file_orderservice_proto_init() {
	if File_orderservice_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderservice_proto_rawDesc), len(file_orderservice_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderservice_proto_goTypes,
		DependencyIndexes: file_orderservice_proto_depIdxs,
		EnumInfos:         file_orderservice_proto_enumTypes,
		MessageInfos:      file_orderservice_proto_msgTypes,
	}.Build()
	File_orderservice_proto = out.File
	file_orderservice_proto_goTypes = nil
	file_orderservice_proto_depIdxs = nil
}
