# syntax=docker/dockerfile:1
FROM  golang:1.24 AS builder
WORKDIR /src/merchant
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -gcflags=all="-N -l" -o /merchant

FROM alpine:latest
COPY --from=builder /merchant /merchant
CMD ["/merchant"]

