// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: deliveryservice.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_GetOrderTracking_FullMethodName    = "/ihavefood.DeliveryService/GetOrderTracking"
	DeliveryService_GetDeliveryFee_FullMethodName      = "/ihavefood.DeliveryService/GetDeliveryFee"
	DeliveryService_ConfirmRiderAccept_FullMethodName  = "/ihavefood.DeliveryService/ConfirmRiderAccept"
	DeliveryService_ConfirmOrderDeliver_FullMethodName = "/ihavefood.DeliveryService/ConfirmOrderDeliver"
	DeliveryService_CreateRider_FullMethodName         = "/ihavefood.DeliveryService/CreateRider"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------DELIVERY SERVICE---------------------------
// Manages riders and delivery process.
type DeliveryServiceClient interface {
	// GetOrderTracking provides real-time updates on the current status and location of
	// an order. It tracks the progress of the order from preparation to delivery,
	// giving the customer real-time status updates.
	//
	// This function should be called from OrderService to track
	GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetOrderTrackingResponse], error)
	// GetDeliveryFee calculates the delivery fee from merchant to customer
	// using merchant ID and customer address ID.
	//
	// Example:
	//
	//	GET /api/deliveries/fee?customer_id=1111&customer_address_id=2222&merchant_id=5555
	GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error)
	// ConfirmRiderAccept updates the order with the rider who accepted it and returns
	// the pickup information.
	ConfirmRiderAccept(ctx context.Context, in *ConfirmRiderAcceptRequest, opts ...grpc.CallOption) (*PickupInfo, error)
	// ConfirmOrderDeliver updates the delivery status after rider has delivered.
	ConfirmOrderDeliver(ctx context.Context, in *ConfirmOrderDeliverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Rider management
	CreateRider(ctx context.Context, in *CreateRiderRequest, opts ...grpc.CallOption) (*Rider, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetOrderTrackingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_GetOrderTracking_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetOrderTrackingRequest, GetOrderTrackingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetOrderTrackingClient = grpc.ServerStreamingClient[GetOrderTrackingResponse]

func (c *deliveryServiceClient) GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryFeeResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ConfirmRiderAccept(ctx context.Context, in *ConfirmRiderAcceptRequest, opts ...grpc.CallOption) (*PickupInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickupInfo)
	err := c.cc.Invoke(ctx, DeliveryService_ConfirmRiderAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ConfirmOrderDeliver(ctx context.Context, in *ConfirmOrderDeliverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeliveryService_ConfirmOrderDeliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CreateRider(ctx context.Context, in *CreateRiderRequest, opts ...grpc.CallOption) (*Rider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rider)
	err := c.cc.Invoke(ctx, DeliveryService_CreateRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
//
// ---------------------DELIVERY SERVICE---------------------------
// Manages riders and delivery process.
type DeliveryServiceServer interface {
	// GetOrderTracking provides real-time updates on the current status and location of
	// an order. It tracks the progress of the order from preparation to delivery,
	// giving the customer real-time status updates.
	//
	// This function should be called from OrderService to track
	GetOrderTracking(*GetOrderTrackingRequest, grpc.ServerStreamingServer[GetOrderTrackingResponse]) error
	// GetDeliveryFee calculates the delivery fee from merchant to customer
	// using merchant ID and customer address ID.
	//
	// Example:
	//
	//	GET /api/deliveries/fee?customer_id=1111&customer_address_id=2222&merchant_id=5555
	GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error)
	// ConfirmRiderAccept updates the order with the rider who accepted it and returns
	// the pickup information.
	ConfirmRiderAccept(context.Context, *ConfirmRiderAcceptRequest) (*PickupInfo, error)
	// ConfirmOrderDeliver updates the delivery status after rider has delivered.
	ConfirmOrderDeliver(context.Context, *ConfirmOrderDeliverRequest) (*emptypb.Empty, error)
	// Rider management
	CreateRider(context.Context, *CreateRiderRequest) (*Rider, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) GetOrderTracking(*GetOrderTrackingRequest, grpc.ServerStreamingServer[GetOrderTrackingResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetOrderTracking not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryFee not implemented")
}
func (UnimplementedDeliveryServiceServer) ConfirmRiderAccept(context.Context, *ConfirmRiderAcceptRequest) (*PickupInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRiderAccept not implemented")
}
func (UnimplementedDeliveryServiceServer) ConfirmOrderDeliver(context.Context, *ConfirmOrderDeliverRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmOrderDeliver not implemented")
}
func (UnimplementedDeliveryServiceServer) CreateRider(context.Context, *CreateRiderRequest) (*Rider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRider not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_GetOrderTracking_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOrderTrackingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).GetOrderTracking(m, &grpc.GenericServerStream[GetOrderTrackingRequest, GetOrderTrackingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetOrderTrackingServer = grpc.ServerStreamingServer[GetOrderTrackingResponse]

func _DeliveryService_GetDeliveryFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryFee(ctx, req.(*GetDeliveryFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ConfirmRiderAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRiderAcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ConfirmRiderAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ConfirmRiderAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ConfirmRiderAccept(ctx, req.(*ConfirmRiderAcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ConfirmOrderDeliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmOrderDeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ConfirmOrderDeliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ConfirmOrderDeliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ConfirmOrderDeliver(ctx, req.(*ConfirmOrderDeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CreateRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CreateRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateRider(ctx, req.(*CreateRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ihavefood.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeliveryFee",
			Handler:    _DeliveryService_GetDeliveryFee_Handler,
		},
		{
			MethodName: "ConfirmRiderAccept",
			Handler:    _DeliveryService_ConfirmRiderAccept_Handler,
		},
		{
			MethodName: "ConfirmOrderDeliver",
			Handler:    _DeliveryService_ConfirmOrderDeliver_Handler,
		},
		{
			MethodName: "CreateRider",
			Handler:    _DeliveryService_CreateRider_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderTracking",
			Handler:       _DeliveryService_GetOrderTracking_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deliveryservice.proto",
}
