// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: deliveryservice.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeliveryService_GetOrderTracking_FullMethodName    = "/ihavefood.DeliveryService/GetOrderTracking"
	DeliveryService_GetDeliveryFee_FullMethodName      = "/ihavefood.DeliveryService/GetDeliveryFee"
	DeliveryService_ConfirmRiderAccept_FullMethodName  = "/ihavefood.DeliveryService/ConfirmRiderAccept"
	DeliveryService_ConfirmOrderDeliver_FullMethodName = "/ihavefood.DeliveryService/ConfirmOrderDeliver"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	// GetOrderTracking provides real-time updates on the current status and location of
	// an order. It tracks the progress of the order from preparation to delivery,
	// giving the user real-time status updates.
	//
	// This function should be called from OrderService to track
	GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (DeliveryService_GetOrderTrackingClient, error)
	// GetDeliveryFee calculates and returns the delivery fee based on the distance
	// between the user's location and the restaurant's location.
	GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error)
	// ConfirmRiderAccept updates the order with the rider who accepted it and returns
	// the pickup information.
	ConfirmRiderAccept(ctx context.Context, in *ConfirmRiderAcceptRequest, opts ...grpc.CallOption) (*PickupInfo, error)
	// ConfirmOrderDeliver updates the delivery status after rider has delivered.
	ConfirmOrderDeliver(ctx context.Context, in *ConfirmOrderDeliverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (DeliveryService_GetOrderTrackingClient, error) {
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_GetOrderTracking_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &deliveryServiceGetOrderTrackingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeliveryService_GetOrderTrackingClient interface {
	Recv() (*GetOrderTrackingResponse, error)
	grpc.ClientStream
}

type deliveryServiceGetOrderTrackingClient struct {
	grpc.ClientStream
}

func (x *deliveryServiceGetOrderTrackingClient) Recv() (*GetOrderTrackingResponse, error) {
	m := new(GetOrderTrackingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deliveryServiceClient) GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error) {
	out := new(GetDeliveryFeeResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryFee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ConfirmRiderAccept(ctx context.Context, in *ConfirmRiderAcceptRequest, opts ...grpc.CallOption) (*PickupInfo, error) {
	out := new(PickupInfo)
	err := c.cc.Invoke(ctx, DeliveryService_ConfirmRiderAccept_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ConfirmOrderDeliver(ctx context.Context, in *ConfirmOrderDeliverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeliveryService_ConfirmOrderDeliver_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility
type DeliveryServiceServer interface {
	// GetOrderTracking provides real-time updates on the current status and location of
	// an order. It tracks the progress of the order from preparation to delivery,
	// giving the user real-time status updates.
	//
	// This function should be called from OrderService to track
	GetOrderTracking(*GetOrderTrackingRequest, DeliveryService_GetOrderTrackingServer) error
	// GetDeliveryFee calculates and returns the delivery fee based on the distance
	// between the user's location and the restaurant's location.
	GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error)
	// ConfirmRiderAccept updates the order with the rider who accepted it and returns
	// the pickup information.
	ConfirmRiderAccept(context.Context, *ConfirmRiderAcceptRequest) (*PickupInfo, error)
	// ConfirmOrderDeliver updates the delivery status after rider has delivered.
	ConfirmOrderDeliver(context.Context, *ConfirmOrderDeliverRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeliveryServiceServer struct {
}

func (UnimplementedDeliveryServiceServer) GetOrderTracking(*GetOrderTrackingRequest, DeliveryService_GetOrderTrackingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOrderTracking not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryFee not implemented")
}
func (UnimplementedDeliveryServiceServer) ConfirmRiderAccept(context.Context, *ConfirmRiderAcceptRequest) (*PickupInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRiderAccept not implemented")
}
func (UnimplementedDeliveryServiceServer) ConfirmOrderDeliver(context.Context, *ConfirmOrderDeliverRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmOrderDeliver not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_GetOrderTracking_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOrderTrackingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).GetOrderTracking(m, &deliveryServiceGetOrderTrackingServer{stream})
}

type DeliveryService_GetOrderTrackingServer interface {
	Send(*GetOrderTrackingResponse) error
	grpc.ServerStream
}

type deliveryServiceGetOrderTrackingServer struct {
	grpc.ServerStream
}

func (x *deliveryServiceGetOrderTrackingServer) Send(m *GetOrderTrackingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeliveryService_GetDeliveryFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryFee(ctx, req.(*GetDeliveryFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ConfirmRiderAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRiderAcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ConfirmRiderAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ConfirmRiderAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ConfirmRiderAccept(ctx, req.(*ConfirmRiderAcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ConfirmOrderDeliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmOrderDeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ConfirmOrderDeliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ConfirmOrderDeliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ConfirmOrderDeliver(ctx, req.(*ConfirmOrderDeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ihavefood.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeliveryFee",
			Handler:    _DeliveryService_GetDeliveryFee_Handler,
		},
		{
			MethodName: "ConfirmRiderAccept",
			Handler:    _DeliveryService_ConfirmRiderAccept_Handler,
		},
		{
			MethodName: "ConfirmOrderDeliver",
			Handler:    _DeliveryService_ConfirmOrderDeliver_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderTracking",
			Handler:       _DeliveryService_GetOrderTracking_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deliveryservice.proto",
}
