// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: restaurantservice.proto

package genproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantStatus int32

const (
	RestaurantStatus_CLOSED RestaurantStatus = 0
	RestaurantStatus_OPEN   RestaurantStatus = 1
)

// Enum value maps for RestaurantStatus.
var (
	RestaurantStatus_name = map[int32]string{
		0: "CLOSED",
		1: "OPEN",
	}
	RestaurantStatus_value = map[string]int32{
		"CLOSED": 0,
		"OPEN":   1,
	}
)

func (x RestaurantStatus) Enum() *RestaurantStatus {
	p := new(RestaurantStatus)
	*p = x
	return p
}

func (x RestaurantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestaurantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_restaurantservice_proto_enumTypes[0].Descriptor()
}

func (RestaurantStatus) Type() protoreflect.EnumType {
	return &file_restaurantservice_proto_enumTypes[0]
}

func (x RestaurantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestaurantStatus.Descriptor instead.
func (RestaurantStatus) EnumDescriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{0}
}

type Restaurant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantNo string           `protobuf:"bytes,1,opt,name=restaurant_no,json=restaurantNo,proto3" json:"restaurant_no,omitempty"`
	Name         string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Menus        []*Menu          `protobuf:"bytes,3,rep,name=menus,proto3" json:"menus,omitempty"`
	Address      *Address         `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Status       RestaurantStatus `protobuf:"varint,5,opt,name=status,proto3,enum=ihavefood.RestaurantStatus" json:"status,omitempty"`
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{0}
}

func (x *Restaurant) GetRestaurantNo() string {
	if x != nil {
		return x.RestaurantNo
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *Restaurant) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Restaurant) GetStatus() RestaurantStatus {
	if x != nil {
		return x.Status
	}
	return RestaurantStatus_CLOSED
}

type Menu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodName string `protobuf:"bytes,1,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	Price    int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Menu) Reset() {
	*x = Menu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetFoodName() string {
	if x != nil {
		return x.FoodName
	}
	return ""
}

func (x *Menu) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantNo string `protobuf:"bytes,1,opt,name=restaurant_no,json=restaurantNo,proto3" json:"restaurant_no,omitempty"`
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantRequest) GetRestaurantNo() string {
	if x != nil {
		return x.RestaurantNo
	}
	return ""
}

type GetRestaurantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restaurant *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
}

func (x *GetRestaurantResponse) Reset() {
	*x = GetRestaurantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantResponse) ProtoMessage() {}

func (x *GetRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantResponse) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type ListRestaurantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restaurants []*Restaurant `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
}

func (x *ListRestaurantResponse) Reset() {
	*x = ListRestaurantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantResponse) ProtoMessage() {}

func (x *ListRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantResponse.ProtoReflect.Descriptor instead.
func (*ListRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{4}
}

func (x *ListRestaurantResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type RegisterRestaurantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantName string   `protobuf:"bytes,1,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	Menus          []*Menu  `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	Address        *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RegisterRestaurantRequest) Reset() {
	*x = RegisterRestaurantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRestaurantRequest) ProtoMessage() {}

func (x *RegisterRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRestaurantRequest.ProtoReflect.Descriptor instead.
func (*RegisterRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRestaurantRequest) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *RegisterRestaurantRequest) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *RegisterRestaurantRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type RegisterRestaurantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantNo string `protobuf:"bytes,1,opt,name=restaurant_no,json=restaurantNo,proto3" json:"restaurant_no,omitempty"`
}

func (x *RegisterRestaurantResponse) Reset() {
	*x = RegisterRestaurantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRestaurantResponse) ProtoMessage() {}

func (x *RegisterRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRestaurantResponse.ProtoReflect.Descriptor instead.
func (*RegisterRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRestaurantResponse) GetRestaurantNo() string {
	if x != nil {
		return x.RestaurantNo
	}
	return ""
}

type AddMenuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantNo string  `protobuf:"bytes,1,opt,name=restaurant_no,json=restaurantNo,proto3" json:"restaurant_no,omitempty"`
	Menus        []*Menu `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
}

func (x *AddMenuRequest) Reset() {
	*x = AddMenuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuRequest) ProtoMessage() {}

func (x *AddMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuRequest.ProtoReflect.Descriptor instead.
func (*AddMenuRequest) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{7}
}

func (x *AddMenuRequest) GetRestaurantNo() string {
	if x != nil {
		return x.RestaurantNo
	}
	return ""
}

func (x *AddMenuRequest) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type AddMenuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddMenuResponse) Reset() {
	*x = AddMenuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuResponse) ProtoMessage() {}

func (x *AddMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuResponse.ProtoReflect.Descriptor instead.
func (*AddMenuResponse) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{8}
}

func (x *AddMenuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OrderReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo      string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	RestaurantNo string `protobuf:"bytes,2,opt,name=restaurant_no,json=restaurantNo,proto3" json:"restaurant_no,omitempty"`
}

func (x *OrderReadyRequest) Reset() {
	*x = OrderReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadyRequest) ProtoMessage() {}

func (x *OrderReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadyRequest.ProtoReflect.Descriptor instead.
func (*OrderReadyRequest) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{9}
}

func (x *OrderReadyRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderReadyRequest) GetRestaurantNo() string {
	if x != nil {
		return x.RestaurantNo
	}
	return ""
}

type OrderReadyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *OrderReadyResponse) Reset() {
	*x = OrderReadyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurantservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadyResponse) ProtoMessage() {}

func (x *OrderReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadyResponse.ProtoReflect.Descriptor instead.
func (*OrderReadyResponse) Descriptor() ([]byte, []int) {
	return file_restaurantservice_proto_rawDescGZIP(), []int{10}
}

func (x *OrderReadyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_restaurantservice_proto protoreflect.FileDescriptor

var file_restaurantservice_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x68, 0x61, 0x76, 0x65,
	0x66, 0x6f, 0x6f, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01,
	0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x69, 0x68, 0x61,
	0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x39, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e, 0x6f, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f,
	0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x0b, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x19, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x68, 0x61, 0x76,
	0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e, 0x6f, 0x22, 0x5c, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e, 0x6f,
	0x12, 0x25, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x53, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x4e, 0x6f, 0x22, 0x2e, 0x0a, 0x12, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45,
	0x4e, 0x10, 0x01, 0x32, 0xaa, 0x04, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x69, 0x68, 0x61,
	0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x68,
	0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x22, 0x12, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x7b, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x7d, 0x12, 0x65, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x21, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x7e,
	0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x69, 0x68, 0x61,
	0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x63,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x19, 0x2e, 0x69, 0x68, 0x61, 0x76,
	0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x6d, 0x65,
	0x6e, 0x75, 0x73, 0x12, 0x4b, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x12, 0x1c, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_restaurantservice_proto_rawDescOnce sync.Once
	file_restaurantservice_proto_rawDescData = file_restaurantservice_proto_rawDesc
)

func file_restaurantservice_proto_rawDescGZIP() []byte {
	file_restaurantservice_proto_rawDescOnce.Do(func() {
		file_restaurantservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_restaurantservice_proto_rawDescData)
	})
	return file_restaurantservice_proto_rawDescData
}

var file_restaurantservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_restaurantservice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_restaurantservice_proto_goTypes = []interface{}{
	(RestaurantStatus)(0),              // 0: ihavefood.RestaurantStatus
	(*Restaurant)(nil),                 // 1: ihavefood.Restaurant
	(*Menu)(nil),                       // 2: ihavefood.Menu
	(*GetRestaurantRequest)(nil),       // 3: ihavefood.GetRestaurantRequest
	(*GetRestaurantResponse)(nil),      // 4: ihavefood.GetRestaurantResponse
	(*ListRestaurantResponse)(nil),     // 5: ihavefood.ListRestaurantResponse
	(*RegisterRestaurantRequest)(nil),  // 6: ihavefood.RegisterRestaurantRequest
	(*RegisterRestaurantResponse)(nil), // 7: ihavefood.RegisterRestaurantResponse
	(*AddMenuRequest)(nil),             // 8: ihavefood.AddMenuRequest
	(*AddMenuResponse)(nil),            // 9: ihavefood.AddMenuResponse
	(*OrderReadyRequest)(nil),          // 10: ihavefood.OrderReadyRequest
	(*OrderReadyResponse)(nil),         // 11: ihavefood.OrderReadyResponse
	(*Address)(nil),                    // 12: ihavefood.Address
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_restaurantservice_proto_depIdxs = []int32{
	2,  // 0: ihavefood.Restaurant.menus:type_name -> ihavefood.Menu
	12, // 1: ihavefood.Restaurant.address:type_name -> ihavefood.Address
	0,  // 2: ihavefood.Restaurant.status:type_name -> ihavefood.RestaurantStatus
	1,  // 3: ihavefood.GetRestaurantResponse.restaurant:type_name -> ihavefood.Restaurant
	1,  // 4: ihavefood.ListRestaurantResponse.restaurants:type_name -> ihavefood.Restaurant
	2,  // 5: ihavefood.RegisterRestaurantRequest.menus:type_name -> ihavefood.Menu
	12, // 6: ihavefood.RegisterRestaurantRequest.address:type_name -> ihavefood.Address
	2,  // 7: ihavefood.AddMenuRequest.menus:type_name -> ihavefood.Menu
	3,  // 8: ihavefood.RestaurantService.GetRestaurant:input_type -> ihavefood.GetRestaurantRequest
	13, // 9: ihavefood.RestaurantService.ListRestaurant:input_type -> google.protobuf.Empty
	6,  // 10: ihavefood.RestaurantService.RegisterRestaurant:input_type -> ihavefood.RegisterRestaurantRequest
	8,  // 11: ihavefood.RestaurantService.AddMenu:input_type -> ihavefood.AddMenuRequest
	10, // 12: ihavefood.RestaurantService.OrderReady:input_type -> ihavefood.OrderReadyRequest
	4,  // 13: ihavefood.RestaurantService.GetRestaurant:output_type -> ihavefood.GetRestaurantResponse
	5,  // 14: ihavefood.RestaurantService.ListRestaurant:output_type -> ihavefood.ListRestaurantResponse
	7,  // 15: ihavefood.RestaurantService.RegisterRestaurant:output_type -> ihavefood.RegisterRestaurantResponse
	9,  // 16: ihavefood.RestaurantService.AddMenu:output_type -> ihavefood.AddMenuResponse
	11, // 17: ihavefood.RestaurantService.OrderReady:output_type -> ihavefood.OrderReadyResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_restaurantservice_proto_init() }
func file_restaurantservice_proto_init() {
	if File_restaurantservice_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_restaurantservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Restaurant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Menu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRestaurantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRestaurantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRestaurantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRestaurantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRestaurantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMenuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMenuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurantservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReadyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_restaurantservice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurantservice_proto_goTypes,
		DependencyIndexes: file_restaurantservice_proto_depIdxs,
		EnumInfos:         file_restaurantservice_proto_enumTypes,
		MessageInfos:      file_restaurantservice_proto_msgTypes,
	}.Build()
	File_restaurantservice_proto = out.File
	file_restaurantservice_proto_rawDesc = nil
	file_restaurantservice_proto_goTypes = nil
	file_restaurantservice_proto_depIdxs = nil
}
