// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: deliveryservice.proto

package genproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Rider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *Rider) Reset() {
	*x = Rider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rider) ProtoMessage() {}

func (x *Rider) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rider.ProtoReflect.Descriptor instead.
func (*Rider) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{1}
}

func (x *Rider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rider) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type PickupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// pickup_code is a simplified code used for identifying an order
	// for the rider. use three digit i.e 712 , 415
	PickupCode     string `protobuf:"bytes,2,opt,name=pickup_code,json=pickupCode,proto3" json:"pickup_code,omitempty"`
	PickupLocation *Point `protobuf:"bytes,3,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	Destination    *Point `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *PickupInfo) Reset() {
	*x = PickupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupInfo) ProtoMessage() {}

func (x *PickupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupInfo.ProtoReflect.Descriptor instead.
func (*PickupInfo) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{2}
}

func (x *PickupInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PickupInfo) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

func (x *PickupInfo) GetPickupLocation() *Point {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *PickupInfo) GetDestination() *Point {
	if x != nil {
		return x.Destination
	}
	return nil
}

type GetOrderTrackingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
}

func (x *GetOrderTrackingRequest) Reset() {
	*x = GetOrderTrackingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderTrackingRequest) ProtoMessage() {}

func (x *GetOrderTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderTrackingRequest.ProtoReflect.Descriptor instead.
func (*GetOrderTrackingRequest) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderTrackingRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderTrackingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo       string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	RiderId       string `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderLocation *Point `protobuf:"bytes,3,opt,name=rider_location,json=riderLocation,proto3" json:"rider_location,omitempty"`
	UpdateTime    int64  `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *GetOrderTrackingResponse) Reset() {
	*x = GetOrderTrackingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderTrackingResponse) ProtoMessage() {}

func (x *GetOrderTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderTrackingResponse.ProtoReflect.Descriptor instead.
func (*GetOrderTrackingResponse) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderTrackingResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderTrackingResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *GetOrderTrackingResponse) GetRiderLocation() *Point {
	if x != nil {
		return x.RiderLocation
	}
	return nil
}

func (x *GetOrderTrackingResponse) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CalculateDeliveryFeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress       *Address `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	RestaurantAddress *Address `protobuf:"bytes,2,opt,name=restaurant_address,json=restaurantAddress,proto3" json:"restaurant_address,omitempty"`
}

func (x *CalculateDeliveryFeeRequest) Reset() {
	*x = CalculateDeliveryFeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateDeliveryFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDeliveryFeeRequest) ProtoMessage() {}

func (x *CalculateDeliveryFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDeliveryFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateDeliveryFeeRequest) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateDeliveryFeeRequest) GetUserAddress() *Address {
	if x != nil {
		return x.UserAddress
	}
	return nil
}

func (x *CalculateDeliveryFeeRequest) GetRestaurantAddress() *Address {
	if x != nil {
		return x.RestaurantAddress
	}
	return nil
}

type CalculateDeliveryFeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryFee int32 `protobuf:"varint,1,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
}

func (x *CalculateDeliveryFeeResponse) Reset() {
	*x = CalculateDeliveryFeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateDeliveryFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDeliveryFeeResponse) ProtoMessage() {}

func (x *CalculateDeliveryFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDeliveryFeeResponse.ProtoReflect.Descriptor instead.
func (*CalculateDeliveryFeeResponse) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateDeliveryFeeResponse) GetDeliveryFee() int32 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

type ConfirmRiderAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderId string `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	OrderNo string `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
}

func (x *ConfirmRiderAcceptRequest) Reset() {
	*x = ConfirmRiderAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmRiderAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRiderAcceptRequest) ProtoMessage() {}

func (x *ConfirmRiderAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRiderAcceptRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRiderAcceptRequest) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmRiderAcceptRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *ConfirmRiderAcceptRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ConfirmRiderAcceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PickupInfo *PickupInfo `protobuf:"bytes,1,opt,name=pickup_info,json=pickupInfo,proto3" json:"pickup_info,omitempty"`
}

func (x *ConfirmRiderAcceptResponse) Reset() {
	*x = ConfirmRiderAcceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmRiderAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRiderAcceptResponse) ProtoMessage() {}

func (x *ConfirmRiderAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRiderAcceptResponse.ProtoReflect.Descriptor instead.
func (*ConfirmRiderAcceptResponse) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmRiderAcceptResponse) GetPickupInfo() *PickupInfo {
	if x != nil {
		return x.PickupInfo
	}
	return nil
}

type ConfirmOrderDeliverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
}

func (x *ConfirmOrderDeliverRequest) Reset() {
	*x = ConfirmOrderDeliverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmOrderDeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderDeliverRequest) ProtoMessage() {}

func (x *ConfirmOrderDeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderDeliverRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOrderDeliverRequest) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmOrderDeliverRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ConfirmOrderDeliverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ConfirmOrderDeliverResponse) Reset() {
	*x = ConfirmOrderDeliverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmOrderDeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderDeliverResponse) ProtoMessage() {}

func (x *ConfirmOrderDeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderDeliverResponse.ProtoReflect.Descriptor instead.
func (*ConfirmOrderDeliverResponse) Descriptor() ([]byte, []int) {
	return file_deliveryservice_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmOrderDeliverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_deliveryservice_proto protoreflect.FileDescriptor

var file_deliveryservice_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f,
	0x6f, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41,
	0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x22, 0x4e, 0x0a, 0x05, 0x52, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0xb7, 0x01, 0x0a, 0x0a, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x0f,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f,
	0x64, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69,
	0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0e, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69,
	0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0d,
	0x72, 0x69, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x97,
	0x01, 0x0a, 0x1b, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x41, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x11, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x1c, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x22, 0x51, 0x0a, 0x19, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x69, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x54,
	0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x69, 0x64, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x50, 0x69,
	0x63, 0x6b, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x37, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x37, 0x0a,
	0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xa0, 0x04, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x22,
	0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x87, 0x01, 0x0a, 0x14,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x46, 0x65, 0x65, 0x12, 0x26, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x46, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69,
	0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a,
	0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x2f, 0x66, 0x65, 0x65, 0x12, 0x8d, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x69, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x24, 0x2e, 0x69,
	0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x69, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x69, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x24, 0x3a, 0x01, 0x2a, 0x22, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x91, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x12, 0x25, 0x2e,
	0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69, 0x68, 0x61, 0x76, 0x65, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x25, 0x3a, 0x01, 0x2a, 0x22, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deliveryservice_proto_rawDescOnce sync.Once
	file_deliveryservice_proto_rawDescData = file_deliveryservice_proto_rawDesc
)

func file_deliveryservice_proto_rawDescGZIP() []byte {
	file_deliveryservice_proto_rawDescOnce.Do(func() {
		file_deliveryservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_deliveryservice_proto_rawDescData)
	})
	return file_deliveryservice_proto_rawDescData
}

var file_deliveryservice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_deliveryservice_proto_goTypes = []interface{}{
	(*Point)(nil),                        // 0: ihavefood.Point
	(*Rider)(nil),                        // 1: ihavefood.Rider
	(*PickupInfo)(nil),                   // 2: ihavefood.PickupInfo
	(*GetOrderTrackingRequest)(nil),      // 3: ihavefood.GetOrderTrackingRequest
	(*GetOrderTrackingResponse)(nil),     // 4: ihavefood.GetOrderTrackingResponse
	(*CalculateDeliveryFeeRequest)(nil),  // 5: ihavefood.CalculateDeliveryFeeRequest
	(*CalculateDeliveryFeeResponse)(nil), // 6: ihavefood.CalculateDeliveryFeeResponse
	(*ConfirmRiderAcceptRequest)(nil),    // 7: ihavefood.ConfirmRiderAcceptRequest
	(*ConfirmRiderAcceptResponse)(nil),   // 8: ihavefood.ConfirmRiderAcceptResponse
	(*ConfirmOrderDeliverRequest)(nil),   // 9: ihavefood.ConfirmOrderDeliverRequest
	(*ConfirmOrderDeliverResponse)(nil),  // 10: ihavefood.ConfirmOrderDeliverResponse
	(*Address)(nil),                      // 11: ihavefood.Address
}
var file_deliveryservice_proto_depIdxs = []int32{
	0,  // 0: ihavefood.PickupInfo.pickup_location:type_name -> ihavefood.Point
	0,  // 1: ihavefood.PickupInfo.destination:type_name -> ihavefood.Point
	0,  // 2: ihavefood.GetOrderTrackingResponse.rider_location:type_name -> ihavefood.Point
	11, // 3: ihavefood.CalculateDeliveryFeeRequest.user_address:type_name -> ihavefood.Address
	11, // 4: ihavefood.CalculateDeliveryFeeRequest.restaurant_address:type_name -> ihavefood.Address
	2,  // 5: ihavefood.ConfirmRiderAcceptResponse.pickup_info:type_name -> ihavefood.PickupInfo
	3,  // 6: ihavefood.DeliveryService.GetOrderTracking:input_type -> ihavefood.GetOrderTrackingRequest
	5,  // 7: ihavefood.DeliveryService.CalculateDeliveryFee:input_type -> ihavefood.CalculateDeliveryFeeRequest
	7,  // 8: ihavefood.DeliveryService.ConfirmRiderAccept:input_type -> ihavefood.ConfirmRiderAcceptRequest
	9,  // 9: ihavefood.DeliveryService.ConfirmOrderDeliver:input_type -> ihavefood.ConfirmOrderDeliverRequest
	4,  // 10: ihavefood.DeliveryService.GetOrderTracking:output_type -> ihavefood.GetOrderTrackingResponse
	6,  // 11: ihavefood.DeliveryService.CalculateDeliveryFee:output_type -> ihavefood.CalculateDeliveryFeeResponse
	8,  // 12: ihavefood.DeliveryService.ConfirmRiderAccept:output_type -> ihavefood.ConfirmRiderAcceptResponse
	10, // 13: ihavefood.DeliveryService.ConfirmOrderDeliver:output_type -> ihavefood.ConfirmOrderDeliverResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_deliveryservice_proto_init() }
func file_deliveryservice_proto_init() {
	if File_deliveryservice_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_deliveryservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderTrackingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderTrackingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateDeliveryFeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateDeliveryFeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmRiderAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmRiderAcceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmOrderDeliverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmOrderDeliverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deliveryservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deliveryservice_proto_goTypes,
		DependencyIndexes: file_deliveryservice_proto_depIdxs,
		MessageInfos:      file_deliveryservice_proto_msgTypes,
	}.Build()
	File_deliveryservice_proto = out.File
	file_deliveryservice_proto_rawDesc = nil
	file_deliveryservice_proto_goTypes = nil
	file_deliveryservice_proto_depIdxs = nil
}
