// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: customerservice.proto

package genproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	Username     string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// bytes picture = 3;
	Bio    string  `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Social *Social `protobuf:"bytes,5,opt,name=social,proto3" json:"social,omitempty"`
	// User can have many address
	Addresses     []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

func (x *Customer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Customer) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Customer) GetSocial() *Social {
	if x != nil {
		return x.Social
	}
	return nil
}

func (x *Customer) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Customer) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Customer) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ListCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_customerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{1}
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_customerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{2}
}

func (x *ListCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid  string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_customerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid  string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_customerservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCustomerRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

func (x *CreateCustomerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid  string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_customerservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAddressRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

func (x *CreateAddressRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateCustomerRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	// username must has constraint for update
	// such as update every XX months.
	NewUsername string `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	// bytes new_picture = 3;
	NewBio        string  `protobuf:"bytes,4,opt,name=new_bio,json=newBio,proto3" json:"new_bio,omitempty"`
	NewSocial     *Social `protobuf:"bytes,5,opt,name=new_social,json=newSocial,proto3" json:"new_social,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_customerservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCustomerRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

func (x *UpdateCustomerRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

func (x *UpdateCustomerRequest) GetNewBio() string {
	if x != nil {
		return x.NewBio
	}
	return ""
}

func (x *UpdateCustomerRequest) GetNewSocial() *Social {
	if x != nil {
		return x.NewSocial
	}
	return nil
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerUuid  string                 `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_customerservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerservice_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCustomerRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

var File_customerservice_proto protoreflect.FileDescriptor

const file_customerservice_proto_rawDesc = "" +
	"\n" +
	"\x15customerservice.proto\x12\tihavefood\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"\xb4\x02\n" +
	"\bCustomer\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12)\n" +
	"\x06social\x18\x05 \x01(\v2\x11.ihavefood.SocialR\x06social\x120\n" +
	"\taddresses\x18\x06 \x03(\v2\x12.ihavefood.AddressR\taddresses\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x16\n" +
	"\x14ListCustomersRequest\"J\n" +
	"\x15ListCustomersResponse\x121\n" +
	"\tcustomers\x18\x01 \x03(\v2\x13.ihavefood.CustomerR\tcustomers\"9\n" +
	"\x12GetCustomerRequest\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid\"X\n" +
	"\x15CreateCustomerRequest\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"i\n" +
	"\x14CreateAddressRequest\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid\x12,\n" +
	"\aaddress\x18\x02 \x01(\v2\x12.ihavefood.AddressR\aaddress\"\xaa\x01\n" +
	"\x15UpdateCustomerRequest\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\x12\x17\n" +
	"\anew_bio\x18\x04 \x01(\tR\x06newBio\x120\n" +
	"\n" +
	"new_social\x18\x05 \x01(\v2\x11.ihavefood.SocialR\tnewSocial\"<\n" +
	"\x15DeleteCustomerRequest\x12#\n" +
	"\rcustomer_uuid\x18\x01 \x01(\tR\fcustomerUuid2\x95\x05\n" +
	"\x0fCustomerService\x12j\n" +
	"\rListCustomers\x12\x1f.ihavefood.ListCustomersRequest\x1a .ihavefood.ListCustomersResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/customers\x12i\n" +
	"\vGetCustomer\x12\x1d.ihavefood.GetCustomerRequest\x1a\x13.ihavefood.Customer\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/customers/{customer_uuid}\x12I\n" +
	"\x0eCreateCustomer\x12 .ihavefood.CreateCustomerRequest\x1a\x13.ihavefood.Customer\"\x00\x12x\n" +
	"\rCreateAddress\x12\x1f.ihavefood.CreateAddressRequest\x1a\x13.ihavefood.Customer\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/customers/{customer_uuid}/address\x12r\n" +
	"\x0eUpdateCustomer\x12 .ihavefood.UpdateCustomerRequest\x1a\x13.ihavefood.Customer\")\x82\xd3\xe4\x93\x02#:\x01*2\x1e/api/customers/{customer_uuid}\x12r\n" +
	"\x0eDeleteCustomer\x12 .ihavefood.DeleteCustomerRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 *\x1e/api/customers/{customer_uuid}B\vZ\t/genprotob\x06proto3"

var (
	file_customerservice_proto_rawDescOnce sync.Once
	file_customerservice_proto_rawDescData []byte
)

func file_customerservice_proto_rawDescGZIP() []byte {
	file_customerservice_proto_rawDescOnce.Do(func() {
		file_customerservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customerservice_proto_rawDesc), len(file_customerservice_proto_rawDesc)))
	})
	return file_customerservice_proto_rawDescData
}

var file_customerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_customerservice_proto_goTypes = []any{
	(*Customer)(nil),              // 0: ihavefood.Customer
	(*ListCustomersRequest)(nil),  // 1: ihavefood.ListCustomersRequest
	(*ListCustomersResponse)(nil), // 2: ihavefood.ListCustomersResponse
	(*GetCustomerRequest)(nil),    // 3: ihavefood.GetCustomerRequest
	(*CreateCustomerRequest)(nil), // 4: ihavefood.CreateCustomerRequest
	(*CreateAddressRequest)(nil),  // 5: ihavefood.CreateAddressRequest
	(*UpdateCustomerRequest)(nil), // 6: ihavefood.UpdateCustomerRequest
	(*DeleteCustomerRequest)(nil), // 7: ihavefood.DeleteCustomerRequest
	(*Social)(nil),                // 8: ihavefood.Social
	(*Address)(nil),               // 9: ihavefood.Address
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_customerservice_proto_depIdxs = []int32{
	8,  // 0: ihavefood.Customer.social:type_name -> ihavefood.Social
	9,  // 1: ihavefood.Customer.addresses:type_name -> ihavefood.Address
	10, // 2: ihavefood.Customer.create_time:type_name -> google.protobuf.Timestamp
	10, // 3: ihavefood.Customer.update_time:type_name -> google.protobuf.Timestamp
	0,  // 4: ihavefood.ListCustomersResponse.customers:type_name -> ihavefood.Customer
	9,  // 5: ihavefood.CreateAddressRequest.address:type_name -> ihavefood.Address
	8,  // 6: ihavefood.UpdateCustomerRequest.new_social:type_name -> ihavefood.Social
	1,  // 7: ihavefood.CustomerService.ListCustomers:input_type -> ihavefood.ListCustomersRequest
	3,  // 8: ihavefood.CustomerService.GetCustomer:input_type -> ihavefood.GetCustomerRequest
	4,  // 9: ihavefood.CustomerService.CreateCustomer:input_type -> ihavefood.CreateCustomerRequest
	5,  // 10: ihavefood.CustomerService.CreateAddress:input_type -> ihavefood.CreateAddressRequest
	6,  // 11: ihavefood.CustomerService.UpdateCustomer:input_type -> ihavefood.UpdateCustomerRequest
	7,  // 12: ihavefood.CustomerService.DeleteCustomer:input_type -> ihavefood.DeleteCustomerRequest
	2,  // 13: ihavefood.CustomerService.ListCustomers:output_type -> ihavefood.ListCustomersResponse
	0,  // 14: ihavefood.CustomerService.GetCustomer:output_type -> ihavefood.Customer
	0,  // 15: ihavefood.CustomerService.CreateCustomer:output_type -> ihavefood.Customer
	0,  // 16: ihavefood.CustomerService.CreateAddress:output_type -> ihavefood.Customer
	0,  // 17: ihavefood.CustomerService.UpdateCustomer:output_type -> ihavefood.Customer
	11, // 18: ihavefood.CustomerService.DeleteCustomer:output_type -> google.protobuf.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_customerservice_proto_init() }
func file_customerservice_proto_init() {
	if File_customerservice_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customerservice_proto_rawDesc), len(file_customerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customerservice_proto_goTypes,
		DependencyIndexes: file_customerservice_proto_depIdxs,
		MessageInfos:      file_customerservice_proto_msgTypes,
	}.Build()
	File_customerservice_proto = out.File
	file_customerservice_proto_goTypes = nil
	file_customerservice_proto_depIdxs = nil
}
