// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEvent int32

const (
	OrderEvent_UNSPECIFIED             OrderEvent = 0
	OrderEvent_ORDER_PLACED_EVENT      OrderEvent = 1
	OrderEvent_MERCHANT_ACCEPTED_EVENT OrderEvent = 2
	OrderEvent_RIDER_NOTIFIED_EVENT    OrderEvent = 3
	OrderEvent_RIDER_ASSIGNED_EVENT    OrderEvent = 4
	OrderEvent_RIDER_PICKED_UP_EVENT   OrderEvent = 5
	OrderEvent_RIDER_DELIVERED_EVENT   OrderEvent = 6
	OrderEvent_ORDER_CANCELLED_EVENT   OrderEvent = 7
)

// Enum value maps for OrderEvent.
var (
	OrderEvent_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ORDER_PLACED_EVENT",
		2: "MERCHANT_ACCEPTED_EVENT",
		3: "RIDER_NOTIFIED_EVENT",
		4: "RIDER_ASSIGNED_EVENT",
		5: "RIDER_PICKED_UP_EVENT",
		6: "RIDER_DELIVERED_EVENT",
		7: "ORDER_CANCELLED_EVENT",
	}
	OrderEvent_value = map[string]int32{
		"UNSPECIFIED":             0,
		"ORDER_PLACED_EVENT":      1,
		"MERCHANT_ACCEPTED_EVENT": 2,
		"RIDER_NOTIFIED_EVENT":    3,
		"RIDER_ASSIGNED_EVENT":    4,
		"RIDER_PICKED_UP_EVENT":   5,
		"RIDER_DELIVERED_EVENT":   6,
		"ORDER_CANCELLED_EVENT":   7,
	}
)

func (x OrderEvent) Enum() *OrderEvent {
	p := new(OrderEvent)
	*p = x
	return p
}

func (x OrderEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (OrderEvent) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x OrderEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEvent.Descriptor instead.
func (OrderEvent) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type OrderPlacedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *PlaceOrder            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPlacedEvent) Reset() {
	*x = OrderPlacedEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPlacedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent) ProtoMessage() {}

func (x *OrderPlacedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPlacedEvent) GetOrder() *PlaceOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type MerchantAcceptedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AcceptTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantAcceptedEvent) Reset() {
	*x = MerchantAcceptedEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAcceptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAcceptedEvent) ProtoMessage() {}

func (x *MerchantAcceptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAcceptedEvent.ProtoReflect.Descriptor instead.
func (*MerchantAcceptedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantAcceptedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MerchantAcceptedEvent) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantAcceptedEvent) GetAcceptTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptTime
	}
	return nil
}

type RiderNotifiedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NotifyTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderNotifiedEvent) Reset() {
	*x = RiderNotifiedEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderNotifiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderNotifiedEvent) ProtoMessage() {}

func (x *RiderNotifiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderNotifiedEvent.ProtoReflect.Descriptor instead.
func (*RiderNotifiedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *RiderNotifiedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RiderNotifiedEvent) GetNotifyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotifyTime
	}
	return nil
}

type RiderAssignedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	AssignTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=assign_time,json=assignTime,proto3" json:"assign_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderAssignedEvent) Reset() {
	*x = RiderAssignedEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderAssignedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderAssignedEvent) ProtoMessage() {}

func (x *RiderAssignedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderAssignedEvent.ProtoReflect.Descriptor instead.
func (*RiderAssignedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *RiderAssignedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RiderAssignedEvent) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RiderAssignedEvent) GetAssignTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignTime
	}
	return nil
}

type RiderPickedUpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PickupTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderPickedUpEvent) Reset() {
	*x = RiderPickedUpEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderPickedUpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderPickedUpEvent) ProtoMessage() {}

func (x *RiderPickedUpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderPickedUpEvent.ProtoReflect.Descriptor instead.
func (*RiderPickedUpEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *RiderPickedUpEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RiderPickedUpEvent) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RiderPickedUpEvent) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

type RiderDeliveredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DeliverTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deliver_time,json=deliverTime,proto3" json:"deliver_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderDeliveredEvent) Reset() {
	*x = RiderDeliveredEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderDeliveredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderDeliveredEvent) ProtoMessage() {}

func (x *RiderDeliveredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderDeliveredEvent.ProtoReflect.Descriptor instead.
func (*RiderDeliveredEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *RiderDeliveredEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RiderDeliveredEvent) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RiderDeliveredEvent) GetDeliverTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliverTime
	}
	return nil
}

// ============================ SYNC ========================
type SyncCustomerCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCustomerCreated) Reset() {
	*x = SyncCustomerCreated{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCustomerCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCustomerCreated) ProtoMessage() {}

func (x *SyncCustomerCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCustomerCreated.ProtoReflect.Descriptor instead.
func (*SyncCustomerCreated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *SyncCustomerCreated) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SyncCustomerCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SyncCustomerCreated) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type SyncRiderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRiderCreated) Reset() {
	*x = SyncRiderCreated{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRiderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRiderCreated) ProtoMessage() {}

func (x *SyncRiderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRiderCreated.ProtoReflect.Descriptor instead.
func (*SyncRiderCreated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *SyncRiderCreated) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *SyncRiderCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SyncRiderCreated) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type SyncMerchantCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMerchantCreated) Reset() {
	*x = SyncMerchantCreated{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMerchantCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMerchantCreated) ProtoMessage() {}

func (x *SyncMerchantCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMerchantCreated.ProtoReflect.Descriptor instead.
func (*SyncMerchantCreated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *SyncMerchantCreated) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SyncMerchantCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SyncMerchantCreated) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\tihavefood\x1a\x12orderservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\x10OrderPlacedEvent\x12+\n" +
	"\x05order\x18\x01 \x01(\v2\x15.ihavefood.PlaceOrderR\x05order\"\x90\x01\n" +
	"\x15MerchantAcceptedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12;\n" +
	"\vaccept_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptTime\"l\n" +
	"\x12RiderNotifiedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12;\n" +
	"\vnotify_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"notifyTime\"\x87\x01\n" +
	"\x12RiderAssignedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12;\n" +
	"\vassign_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignTime\"\x87\x01\n" +
	"\x12RiderPickedUpEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12;\n" +
	"\vpickup_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\"\x8a\x01\n" +
	"\x13RiderDeliveredEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12=\n" +
	"\fdeliver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliverTime\"\x89\x01\n" +
	"\x13SyncCustomerCreated\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x80\x01\n" +
	"\x10SyncRiderCreated\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x89\x01\n" +
	"\x13SyncMerchantCreated\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime*\xd7\x01\n" +
	"\n" +
	"OrderEvent\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ORDER_PLACED_EVENT\x10\x01\x12\x1b\n" +
	"\x17MERCHANT_ACCEPTED_EVENT\x10\x02\x12\x18\n" +
	"\x14RIDER_NOTIFIED_EVENT\x10\x03\x12\x18\n" +
	"\x14RIDER_ASSIGNED_EVENT\x10\x04\x12\x19\n" +
	"\x15RIDER_PICKED_UP_EVENT\x10\x05\x12\x19\n" +
	"\x15RIDER_DELIVERED_EVENT\x10\x06\x12\x19\n" +
	"\x15ORDER_CANCELLED_EVENT\x10\aB\vZ\t/genprotob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_events_proto_goTypes = []any{
	(OrderEvent)(0),               // 0: ihavefood.OrderEvent
	(*OrderPlacedEvent)(nil),      // 1: ihavefood.OrderPlacedEvent
	(*MerchantAcceptedEvent)(nil), // 2: ihavefood.MerchantAcceptedEvent
	(*RiderNotifiedEvent)(nil),    // 3: ihavefood.RiderNotifiedEvent
	(*RiderAssignedEvent)(nil),    // 4: ihavefood.RiderAssignedEvent
	(*RiderPickedUpEvent)(nil),    // 5: ihavefood.RiderPickedUpEvent
	(*RiderDeliveredEvent)(nil),   // 6: ihavefood.RiderDeliveredEvent
	(*SyncCustomerCreated)(nil),   // 7: ihavefood.SyncCustomerCreated
	(*SyncRiderCreated)(nil),      // 8: ihavefood.SyncRiderCreated
	(*SyncMerchantCreated)(nil),   // 9: ihavefood.SyncMerchantCreated
	(*PlaceOrder)(nil),            // 10: ihavefood.PlaceOrder
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_events_proto_depIdxs = []int32{
	10, // 0: ihavefood.OrderPlacedEvent.order:type_name -> ihavefood.PlaceOrder
	11, // 1: ihavefood.MerchantAcceptedEvent.accept_time:type_name -> google.protobuf.Timestamp
	11, // 2: ihavefood.RiderNotifiedEvent.notify_time:type_name -> google.protobuf.Timestamp
	11, // 3: ihavefood.RiderAssignedEvent.assign_time:type_name -> google.protobuf.Timestamp
	11, // 4: ihavefood.RiderPickedUpEvent.pickup_time:type_name -> google.protobuf.Timestamp
	11, // 5: ihavefood.RiderDeliveredEvent.deliver_time:type_name -> google.protobuf.Timestamp
	11, // 6: ihavefood.SyncCustomerCreated.create_time:type_name -> google.protobuf.Timestamp
	11, // 7: ihavefood.SyncRiderCreated.create_time:type_name -> google.protobuf.Timestamp
	11, // 8: ihavefood.SyncMerchantCreated.create_time:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_orderservice_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
